rules:
  indent:
    - 2
    - 2
  linebreak-style:
    - 2
    - unix
  quotes:
    - 2
    - single
    - avoid-escape
  semi:
    - 2
    - never

env:
  es6: true
  browser: true
  node: true

extends: 'eslint:recommended'

ecmaFeatures:
  jsx: true
  experimentalObjectRestSpread: true
  modules: true

plugins:
  - react
