rules:
  indent:
    - 2
    - 2
    - SwitchCase: 1

  linebreak-style:
    - 2
    - unix

  no-unused-vars:
    - 2
    - varsIgnorePattern: '(React|mocha)'

  quotes:
    - 2
    - single
    - avoid-escape

  semi:
    - 2
    - never

env:
  es6:     true
  browser: true
  node:    true
  mocha:   true

extends: 'eslint:recommended'

ecmaFeatures:
  jsx: true
  experimentalObjectRestSpread: true
  modules: true

plugins:
  - react
